name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cython=0.29.32
  - numpy=1.21.5
  - pandas=1.4.4
  - streamlit
  - holidays=0.19
  - plotly=5.9.0
  - pystan=2.19.1.1
  - prophet=1.1.2
  - altair=4.2.2
